name: goreleaser
on:
  push:
    tags: ["v*"]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Install fyne-cross
        run: go install github.com/fyne-io/fyne-cross/v2/cmd/fyne-cross@latest
      - name: Cross-compile (linux,win,mac)
        run: |
          fyne-cross linux   --pull --app-id mcpproxy ./cmd/mcpproxy
          fyne-cross windows --pull --app-id mcpproxy ./cmd/mcpproxy
          fyne-cross darwin  --pull --app-id mcpproxy ./cmd/mcpproxy
          echo "fyne-cross output structure:"
          find fyne-cross -type f -name "*mcpproxy*" | head -20
      - uses: goreleaser/goreleaser-action@v5
        with:
          version: v2.3.2
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
